# Generated by Django 5.2.10 on 2026-01-22 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gacha", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Draw",
        ),
    ]
