# Generated by Django 5.2.10 on 2026-01-22 04:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gacha", "0002_delete_draw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prize",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="確率(%)。小数点OK。削除を除いた合計が100.00になるように設定。",
                max_digits=6,
            ),
        ),
    ]
